### ISSUE TITLE
Cannot import name 'init_app' from 'label_studio.ml' for starting the backup 

### ISSUE THREAD

**Issue by whalekeykeeper** [heartexlabs/label-studio#839]
An error occurs when I try to start the backup for labeling.
The error message is : `ImportError: cannot import name 'init_app' from 'label_studio.ml'`

I am working on macOS 10.15.4. I am running python3.8 and label-studio version '1.0.1' in a virtual environment.

**To Reproduce**
1. use the command `label-studio-ml init spacy_backend --script model.py` and get the following message:
```
Congratulations! ML Backend has been successfully initialized in ./spacy_backend
Now start it by using:
label-studio-ml start ./spacy_backend
```
2. Use command `label-studio-ml start ./spacy_backend`
3. See an error:
```
(.venv) ➜  finalProject label-studio-ml start ./spacy_backend
Traceback (most recent call last):
  File "././spacy_backend/_wsgi.py", line 30, in <module>
    from label_studio.ml import init_app
ImportError: cannot import name 'init_app' from 'label_studio.ml' (/PATH/.venv/lib/python3.8/site-packages/label_studio/ml/__init__.py)
```

I expect the backend could be launched which I have succeeded before with an older version of label-studio.

I checked the file `label_studio/ml/__init__.py`, it is nearly empty except for a comment `"""This file and its contents are licensed under the Apache License 2.0. Please see the included NOTICE for copyright information and LICENSE for a copy of the license.
"""` 

**Screenshots**
<img width="810" alt="Screen Shot 2021-04-21 at 3 59 44 PM" src="https://user-images.githubusercontent.com/46596921/115566527-99083200-a2ba-11eb-9c4d-19c97cd6873a.png">

**Environment:**
 - OS: macOS 10.15.4.
 - Label Studio Version 1.0.1

**Additional context**
I tried to copy the old `ml/__init__.py` file to recover the one for this new version, more errors are introduced, 
 so finally I recovered everything.

**Comment by smoreface** [comment]
@whalekeykeeper the label-studio-ml is now in its own repository. You might want to update your import statement to label-studio-ml in your spacy backend file instead of label-studio.ml. That's why the file is now blank in 1.0.1. See https://github.com/heartexlabs/label-studio-ml-backend
